### ISSUE TITLE
"Lowest recorded price" section is missing

### ISSUE THREAD

**Issue by muhasturk** [SteamDatabase/BrowserExtension#104] opened 2022-01-25 19:38 UTC
No longer shown on store page. No other steam releated extensions are enabled.

https://store.steampowered.com/app/1174180/Red_Dead_Redemption_2/

SteamDB Version 3.1.0
Microsoft Edge Version 97.0.1072.69 (Official build) (64-bit)
Windows 11 Home 21H2

**Comment by xPaw** [comment] 2022-01-25 19:40
Duplicate of #102

**Closed by xPaw** 2022-01-25 19:40 UTC
