### ISSUE TITLE
Broken layout on app page with localized steam

### ISSUE THREAD

**Issue by matejss** [SteamDatabase/BrowserExtension#173] opened 2024-06-06 17:06 UTC
Having steam set on a language with longer words (e.g. Polish) causes the layout to break due to longer buttons. SteamDB "Sub {ID}" and "Bundle {ID}" buttons push them to the right.
![firefox_oQ0DGpmBGo](https://github.com/SteamDatabase/BrowserExtension/assets/60019942/55ef0a79-8f08-4212-9cb8-5af9dab13fd3)

**Reproduction step:**
1. Open steam store page
2. Change the website language to Polish
3. Open an app page that contains a bundle (e.g. https://store.steampowered.com/app/784080/MechWarrior_5_Mercenaries/)
4. Note, that SteamDB extension causes the buttons to be pushed to the right, which causes them to spill out of the container

**Tested on:**
Windows 10 22H2
1080p 23.8 inch monitor
Firefox 126.0.1 

### Browser name and version

Firefox 126.0.1

**Comment by xPaw** [comment] 2024-06-06 17:07
Duplicate of #133

**Closed by xPaw** 2024-06-06 17:07 UTC
Labels: bug
