### ISSUE TITLE
show the lowest price in wishlist

### ISSUE THREAD

**Issue by luotianyiismywife** [SteamDatabase/BrowserExtension#155] opened 2023-11-13 18:41 UTC
### Is your feature request related to a problem? Please describe.

1.show the lowest price in wishlist.
2.And if it is lowest price in history show a prompt.

### Describe the solution you'd like

1.Just like https://github.com/IsThereAnyDeal/AugmentedSteam
And they are troubling in it(https://github.com/IsThereAnyDeal/AugmentedSteam/issues/482),maybe you can have a cooperation.

2Alt text is colored red or blue to make user know it(maybe red is better)

### Describe alternatives you've considered

Just like i write in above

**Comment by xPaw** [comment] 2023-11-13 18:43
Duplicate of #134

**Closed by xPaw** 2023-11-13 18:43 UTC
Labels: enhancement
