### ISSUE TITLE
Error on auto-discover queue on Firefox

### ISSUE THREAD

**Issue by Floyd77** [SteamDatabase/BrowserExtension#131] opened 2022-12-25 22:09 UTC
I get this error:

"Failed to generate new queue, trying again in five seconds…"

Console output:
[SteamDB] Failed to generate queue TypeError: /explore/generatenewdiscoveryqueue is not a valid URL.

Firefox 108.0.1 x64

Thanks.

**Comment by xPaw** [comment] 2022-12-25 22:11
Duplicate of #130. The fix is pending a review by Mozilla.

**Closed by xPaw** 2022-12-25 22:11 UTC
