### ISSUE TITLE
Add a button to go to ProtonDB

### ISSUE THREAD

**Issue by Tiagoquix** [SteamDatabase/BrowserExtension#164] opened 2023-12-29 08:06 UTC
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

Add a button to go to ProtonDB from the Steam Store page of an app/game.

![image](https://github.com/SteamDatabase/BrowserExtension/assets/30274161/1390523d-bfa7-4819-97b0-af22c6a952d7)

**Comment by xPaw** [comment] 2023-12-29 18:09
Gonna close as duplicate of #144, you can leave a comment there.

**Closed by xPaw** 2023-12-29 18:09 UTC
Labels: enhancement
